### ISSUE TITLE
Install Scalar

### ISSUE THREAD

**Issue by rcrath** [digiah/2do#136]
from git

**Comment by rcrath** [comment]
install started at dahi.../scalar.  not working yet, stuck on api keys and such, step two of the install.  not sure where to get the google map api, I think soundcloud need the client ID (not the secret key), and I think the public/private keys are the public and secret keys for recaptcha, but not sure.  documentation is unclear.  consult with @damg70 on how to do step 2 of install.txt

**Comment by damg70** [comment]
For Google, the process begins [here](https://developers.google.com/maps/documentation/javascript/tutorial) which requires a Google Account to use... which is why we made a left and rolled over to MapBox/Leaflet. In any case, that link takes you through the process. I haven't looked at the Scalar install process, so I imagine that they are simply asking for your API key at some point via a configuration form. Going through the Google process should result in two things: 1) a snippet of javascript that can be pasted into code, and 2) an actual API key that you can use.

**Comment by damg70** [comment]
Looking more closely at STEP 2 of INSTALL.TXT...
Looks like reCAPTCHA is another feature that requires a Google account to activate. In this situation, as well as the MAPS context above, I think you can use your @hawaii.edu addy to register for MAPS as well. Something to think about tho: do we need a shared google account for analytics and stuff like this? like a DAHI@gmail.com?

Regarding the rest of the implied requirements of step 2, maybe we look at it together...  Looks like the Soundcloud API reference is based on the fact that you can "import" Soundcloud files into Scalar (really just their metatdata). Not having a Soundcloud key may not be an obstacle to the initial install.

**Comment by damg70** [comment]
fixed by raw MAGIC! WALLA!
